const pointstable = [
    {
        team:"CSK(Q)",
        logo:"./teamslogo/csk.png",
        played:13,
        won:9,
        loss:4,
        points:18,
        rr:0.210
    },
    {
        team:"MI(Q)",
        logo:"./teamslogo/mi.png",
        played:13,
        won:8,
        loss:5,

        points:16,
        rr:0.349
        
    },
    {
        team:"RCB",
        logo:"./teamslogo/rcb.png",
        played:12,
        won:4,
        loss:7,
        points:9,
        rr:-0.683
    },
    {
        team:"SRH",
        logo:"./teamslogo/srh.png",
        played:13,
        won:6,
        loss:7,
        points:12,
        rr:+0.654
    },
    {
        team:"RR",
        logo:"./teamslogo/rrr.png",
        played:14,
        won:5,
        loss:8,
        points:11,
        rr:-0.449
    },
    {
        team:"KKR",
        logo:"./teamslogo/kkr.png",
        played:13,
        won:6,
        loss:7,
        points:12,
        rr:0.173
    },
    {
        team:"DC(Q)",
        logo:"./teamslogo/dc.png",
        played:14,
        won:9,
        loss:5,
        points:18,
        rr:0.044
    },
    {
        team:"KXIP",
        logo:"./teamslogo/pj.png",
        played:13,
        won:5,
        loss:8,
        points:10,
        rr:-0.321
       
    },
]
export default pointstable;
