const pointstable = [
    {
        team:"CSK",
        logo:"./teamslogo/csk.png",
        played:12,
        won:8,
        loss:4,
        points:16,
        rr:-0.113
    },
    {
        team:"MI",
        logo:"./teamslogo/mi.png",
        played:11,
        won:7,
        loss:4,

        points:12,
        rr:0.559
        
    },
    {
        team:"RCB",
        logo:"./teamslogo/rcb.png",
        played:11,
        won:4,
        loss:7,
        points:8,
        rr:-0.683
    },
    {
        team:"SRH",
        logo:"./teamslogo/srh.png",
        played:10,
        won:5,
        loss:5,
        points:10,
        rr:+0.654
    },
    {
        team:"RR",
        logo:"./teamslogo/rrr.png",
        played:11,
        won:4,
        loss:7,
        points:8,
        rr:-0.390
    },
    {
        team:"KKR",
        logo:"./teamslogo/kkr.png",
        played:11,
        won:4,
        loss:7,
        points:8,
        rr:-0.053
    },
    {
        team:"DC",
        logo:"./teamslogo/dc.png",
        played:11,
        won:7,
        loss:4,
        points:14,
        rr:+0.180
    },
    {
        team:"KXIP",
        logo:"./teamslogo/pj.png",
        played:11,
        won:5,
        loss:6,
        points:10,
        rr:-0.117
       
    },
]
export default pointstable;
