const pointstable = [
    {
        team:"CSK",
        logo:"./teamslogo/csk.png",
        played:5,
        won:4,
        loss:1,
        points:8,
        rr:0.159
    },
    {
        team:"MI",
        logo:"./teamslogo/mi.png",
        played:5,
        won:3,
        loss:2,

        points:6,
        rr:0.342
        
    },
    {
        team:"RCB",
        logo:"./teamslogo/rcb.png",
        played:5,
        won:0,
        loss:5,
        points:0,
        rr:-1.60
    },
    {
        team:"SRH",
        logo:"./teamslogo/srh.png",
        played:5,
        won:3,
        loss:2,
        points:6,
        rr:+1.00
    },
    {
        team:"RR",
        logo:"./teamslogo/rrr.png",
        played:4,
        won:1,
        loss:3,
        points:2,
        rr:-0.333
    },
    {
        team:"KKR",
        logo:"./teamslogo/kkr.png",
        played:4,
        won:3,
        loss:1,
        points:6,
        rr:+0.534
    },
    {
        team:"DC",
        logo:"./teamslogo/dc.png",
        played:5,
        won:2,
        loss:3,
        points:4,
        rr:+0.029
    },
    {
        team:"KXIP",
        logo:"./teamslogo/pj.png",
        played:5,
        won:3,
        loss:2,
        points:6,
        rr:-0.094
       
    },
]
export default pointstable;
